# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: varint.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'varint.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cvarint.proto\"\x12\n\x05Int64\x12\t\n\x01n\x18\x01 \x01(\x03\"\x12\n\x05Int32\x12\t\n\x01n\x18\x01 \x01(\x05\"\x13\n\x06Uint64\x12\t\n\x01n\x18\x01 \x01(\x04\"\x13\n\x06Sint64\x12\t\n\x01n\x18\x01 \x01(\x12\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'varint_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INT64']._serialized_start=16
  _globals['_INT64']._serialized_end=34
  _globals['_INT32']._serialized_start=36
  _globals['_INT32']._serialized_end=54
  _globals['_UINT64']._serialized_start=56
  _globals['_UINT64']._serialized_end=75
  _globals['_SINT64']._serialized_start=77
  _globals['_SINT64']._serialized_end=96
# @@protoc_insertion_point(module_scope)
